default_language_version:
    python: python3.8
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        args: ['--fix=lf']
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
    - id: black-jupyter
      language_version: python3.8
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", "--ensure-newline-before-comments", "--line-length", "88"]
